import Head from 'next/head';
import Leftsidebar from '../components/Leftsidebar';
import Rightsidebar from '../components/Rightsidebar';

export default function Home() {
  return (
    <div className="flex sm:flex-row flex-col-reverse">
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Leftsidebar  />
		<Rightsidebar />
    </div>
  )
}
